// <auto-generated />
using CatalogService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240318024542_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothing & Apparel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Books & Media"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jewelry & Accessories"
                        });
                });

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sleek black tee: Style redefined. Elevate your look effortlessly! 🔥 #FashionEssential",
                            ImageSource = "~/images/OIP.jpg",
                            Name = "T-Shirt",
                            Price = 299.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Unleash limitless power with our latest cellphone innovation!",
                            ImageSource = "~/images/cellphone.jpg",
                            Name = "Cellphone",
                            Price = 13999.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Unleash precision in the palm of your hand. Elevate your tools with our sleek knife.",
                            ImageSource = "~/images/ec3596459302e2e8e4d586517816a69a.jpg",
                            Name = "Knife",
                            Price = 240.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Indulge in luxury with our hydrating lotion. Elevate your skincare routine effortlessly.",
                            ImageSource = "~/images/lotion.jpg",
                            Name = "Lotion",
                            Price = 250.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Step up your game with our stylish rubber shoes. Elevate your look with every stride.",
                            ImageSource = "~/images/rubbershoes.jpg",
                            Name = "Rubber Shoes",
                            Price = 5500.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Master clean code principles. Robert Martin's essential guide.",
                            ImageSource = "~/images/cleancode.jpg",
                            Name = "Clean Code",
                            Price = 2890.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Immerse in endless adventures. Explore, create, survive. Minecraft awaits!",
                            ImageSource = "~/images/Minecraft.jpg",
                            Name = "Minecraft",
                            Price = 150.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Upgrade your cleaning game with our durable fiber cloth.",
                            ImageSource = "~/images/fibrecloth.jpg",
                            Name = "Fibre Cloth",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Pure nourishment for your pet. Goat's milk: natural goodness.",
                            ImageSource = "~/images/goatsmilk.jpg",
                            Name = "Goat's Milk",
                            Price = 380.0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Elegant luxury, timeless beauty. Elevate your style with 14k gold.",
                            ImageSource = "~/images/necklace.jpg",
                            Name = "14K Gold Necklace",
                            Price = 21500.0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Powerful laptop with high-speed performance. Perfect for work or entertainment on the go.",
                            ImageSource = "~/images/laptop.jpg",
                            Name = "Laptop",
                            Price = 50000.0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Track your fitness, receive notifications, and more, all from your wrist.",
                            ImageSource = "~/images/smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 9999.9500000000007
                        },
                        new
                        {
                            Id = 13,
                            Description = "Enjoy crisp sound quality and freedom from wires with these wireless earbuds.",
                            ImageSource = "~/images/wirelessearbuds.jpg",
                            Name = "Wireless Earbuds",
                            Price = 3999.9499999999998
                        },
                        new
                        {
                            Id = 14,
                            Description = "Take your music anywhere with this portable Bluetooth speaker.",
                            ImageSource = "~/images/bluetoothspeaker.jpg",
                            Name = "Portable Bluetooth Speaker",
                            Price = 2499.9499999999998
                        },
                        new
                        {
                            Id = 15,
                            Description = "Monitor your health and track your fitness goals with this sleek fitness tracker.",
                            ImageSource = "~/images/fitnesstracker.jpg",
                            Name = "Fitness Tracker",
                            Price = 2995.0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Brew your favorite coffee just the way you like it.",
                            ImageSource = "~/images/coffeemaker.jpg",
                            Name = "Coffee Maker",
                            Price = 6850.5
                        },
                        new
                        {
                            Id = 17,
                            Description = "Gentle on gums, powerful on plaque.",
                            ImageSource = "~/images/electrictoothbrush.jpg",
                            Name = "Electric Toothbrush",
                            Price = 1999.0
                        },
                        new
                        {
                            Id = 18,
                            Description = "Capture every moment with stunning clarity using this digital camera.",
                            ImageSource = "~/images/digitalcamera.jpg",
                            Name = "Digital Camera",
                            Price = 14560.6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Enjoy healthier cooking without sacrificing flavor with this air fryer.",
                            ImageSource = "~/images/airfryer.jpg",
                            Name = "Air Fryer",
                            Price = 4499.0
                        },
                        new
                        {
                            Id = 20,
                            Description = "Never run out of battery again with this portable power bank.",
                            ImageSource = "~/images/powerbank.jpg",
                            Name = "Portable Power Bank",
                            Price = 1499.0
                        });
                });

            modelBuilder.Entity("CatalogService.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId", "CategoryId")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("CatalogService.Models.Purchase", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OwnerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CatalogService.Models.ProductCategory", b =>
                {
                    b.HasOne("CatalogService.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Models.Product", "Product")
                        .WithMany("Category")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CatalogService.Models.Purchase", b =>
                {
                    b.HasOne("CatalogService.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
